[theme]
base = "light"
primaryColor = "#087f8c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f5f7"
textColor = "#20262d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"
