[theme]
base = "light"
primaryColor = "#bd4b38"
backgroundColor = "#eef2f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#18211f"
font = "sans serif"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showErrorDetails = "none"
